/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sandbox;

public class Main {
    private Main(String[] args) {
        Sandbox sandbox = new Sandbox(args);
        sandbox.init();
    }

    public static void main(String[] args) {
        new Main(args);
    }
}
